// <auto-generated />
using System;
using EF.Tutorial.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EF.Tutorial.Persistence.Migrations
{
    [DbContext(typeof(TutorialDbContext))]
    partial class TutorialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tutorial")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("COMPANY_UQ1")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Company", "tutorial");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f2c8b6e-4b2e-4bb4-9f31-0b7f4e2b9d9d"),
                            Code = "0000001",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = "Admin",
                            LegalName = "Company 1"
                        },
                        new
                        {
                            Id = new Guid("a1d4cbe2-0d18-4c57-8d8a-7a2de9131df6"),
                            Code = "0000002",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = "Admin",
                            LegalName = "Company 2"
                        });
                });

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalObjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("USER_UQ1")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("ExternalObjectId")
                        .IsUnique()
                        .HasDatabaseName("USER_UQ2")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("User", "tutorial");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3d5b2f4-91a7-4ac6-9c40-2df5f1e7b6a8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = "Admin",
                            DisplayName = "User",
                            Email = "tutorial@test.com",
                            ExternalObjectId = "c624b0ea-1a43-47e4-8c51-d1b64091ef0a"
                        });
                });

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.UserCompanyAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("USERCOMPANYACCESS_UQ1")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("UserCompanyAccess", "tutorial");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0c8a3d9-91c4-44bb-af40-6b77c0dd3d8b"),
                            CompanyId = new Guid("8f2c8b6e-4b2e-4bb4-9f31-0b7f4e2b9d9d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = "Admin",
                            UserId = new Guid("e3d5b2f4-91a7-4ac6-9c40-2df5f1e7b6a8")
                        });
                });

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.UserCompanyAccess", b =>
                {
                    b.HasOne("EF.Tutorial.Persistence.Entities.Company", "Company")
                        .WithMany("UserCompanyAccesses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("USERCOMPANYACCESS_COMPANY_FK");

                    b.HasOne("EF.Tutorial.Persistence.Entities.User", "User")
                        .WithMany("UserCompanyAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("USERCOMPANYACCESS_USER_FK");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.Company", b =>
                {
                    b.Navigation("UserCompanyAccesses");
                });

            modelBuilder.Entity("EF.Tutorial.Persistence.Entities.User", b =>
                {
                    b.Navigation("UserCompanyAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
